// modules/phone/tree/treeWorldInfo.js — World Book 注入
// 把树的状态信息写入世界书条目，让主 LLM 在聊天时能感知树。
// 模式参考 diaryWorldInfo.js，关键差异：关键词触发（非 constant 常驻）。

const TREE_WI_LOG = '[树树WI]';

// ═══════════════════════════════════════════════════════════════════════
// World Book Injection
// ═══════════════════════════════════════════════════════════════════════

/**
 * 将树的状态注入世界书条目 <tree>，
 * 当聊天中提到树相关关键词时触发注入。
 *
 * @param {object} treeState - 树状态对象 (from loadTreeData().treeState)
 * @param {object} seasonInfo - 当前季节 { id, name }
 * @param {object} stageInfo - 当前阶段 { id, name }
 * @param {string} charName - AI 角色名
 * @param {string} userName - 玩家名
 */
export async function updateTreeWorldInfo(treeState, seasonInfo, stageInfo, charName, userName) {
    try {
        const { saveWorldInfo, loadWorldInfo } = await import('../../../../../../world-info.js');
        const { findActiveWorldBook } = await import('../../utils.js');

        const worldBookName = await findActiveWorldBook();
        if (!worldBookName) {
            console.warn(`${TREE_WI_LOG} 未找到活跃的世界书`);
            return;
        }

        const WI_KEY = 'm_tree';
        const wb = await loadWorldInfo(worldBookName);
        let targetEntry = Object.values(wb.entries).find(e => e.key && e.key.includes(WI_KEY));

        const treeName = treeState.treeName || '小树';
        const growthVal = treeState.growth || 0;
        const totalDays = treeState.totalCareDays || 0;

        // Build concise tree status (~100 tokens)
        const entryContent = `
<tree>
【情侣小树】
${charName}和${userName}在手机里共同养育着一棵名叫「${treeName}」的小树。
当前状态：${stageInfo.name}（${seasonInfo.name}），成长值 ${growthVal}。
她们已经一起照顾了 ${totalDays} 天。
这棵树见证着她们之间的感情——每一次浇水、施肥、唱歌、抚摸，都是爱的表达。
</tree>
`;

        // Build keywords: tree name + generic tree keywords
        const keywords = [treeName, WI_KEY, '树树', '手机游戏', '小树', '浇水', '种树', '施肥'];
        // Deduplicate
        const uniqueKeys = [...new Set(keywords)];

        if (!targetEntry) {
            // Create new entry
            let maxId = 0;
            Object.keys(wb.entries).forEach(id => {
                const num = parseInt(id);
                if (!isNaN(num) && num > maxId) maxId = num;
            });
            const newId = maxId + 1;

            wb.entries[newId] = {
                uid: newId,
                key: uniqueKeys,
                comment: '情侣小树状态 (Auto-generated by tree app)',
                content: entryContent,
                constant: false,          // ← 关键词触发，非常驻
                selectiveLogic: 0,        // ANY match
                position: 4,
                depth: 1,
                order: 996,
                disable: false,
                excludeRecursion: true,
                preventRecursion: true,
                displayIndex: 0,
            };
        } else {
            // Update existing entry
            targetEntry.content = entryContent;
            targetEntry.key = uniqueKeys;
            targetEntry.disable = false;
            targetEntry.constant = false;
            targetEntry.selectiveLogic = 0;
            targetEntry.position = 4;
            targetEntry.depth = 1;
            targetEntry.order = 996;
            targetEntry.excludeRecursion = true;
            targetEntry.preventRecursion = true;
        }

        await saveWorldInfo(worldBookName, wb);
        console.log(`${TREE_WI_LOG} World Book 条目已更新：「${treeName}」${stageInfo.name}·${seasonInfo.name}`);
    } catch (e) {
        console.warn(`${TREE_WI_LOG} updateTreeWorldInfo failed:`, e);
    }
}

/**
 * 禁用树的世界书条目（关闭开关时调用）
 */
export async function disableTreeWorldInfo() {
    try {
        const { saveWorldInfo, loadWorldInfo } = await import('../../../../../../world-info.js');
        const { findActiveWorldBook } = await import('../../utils.js');

        const worldBookName = await findActiveWorldBook();
        if (!worldBookName) return;

        const wb = await loadWorldInfo(worldBookName);
        const targetEntry = Object.values(wb.entries).find(e => e.key && e.key.includes('m_tree'));

        if (targetEntry && !targetEntry.disable) {
            targetEntry.disable = true;
            await saveWorldInfo(worldBookName, wb);
            console.log(`${TREE_WI_LOG} World Book 条目已禁用`);
        }
    } catch (e) {
        console.warn(`${TREE_WI_LOG} disableTreeWorldInfo failed:`, e);
    }
}
