// modules/phone/dnd/dndStorage.js — D&D Data Persistence + Cloud Sync
// localStorage (primary) + server sync (backup/cross-device).
// Follows the same pattern as treeStorage.js.

import { getContext } from '../../../../../../extensions.js';
import { apiRequest } from '../moments/apiClient.js';
import { getSettings } from '../moments/state.js';
import { getCampaignById } from './dndCampaigns.js';

const DND_STORAGE_KEY = 'gf_dnd_data_v1';
const DND_LOG = '[D&D]';

// ═══════════════════════════════════════════════════════════════════════
// Default Data Structure
// ═══════════════════════════════════════════════════════════════════════

function createDefaultData() {
    return {
        playerCharacter: null,      // Created via character creation flow
        partnerCharacter: null,     // Auto-generated by LLM

        currentRun: null,           // Active adventure (see below for shape)
        // currentRun shape:
        // {
        //     campaignId: 'lost_mine',
        //     currentRoom: 1,
        //     totalRooms: 4,
        //     narrativeLog: [{ type:'dm'|'action'|'dice'|'partner', text:'...' }],
        //     roomType: 'combat',         // current room event type
        //     inCombat: false,
        //     combatState: null,          // { enemies, turnOrder, currentTurn }
        //     startedAt: '',
        // }

        history: [],
        // history item shape:
        // {
        //     date: '2026-03-16',
        //     campaign: '失落的矿坑',
        //     campaignId: 'lost_mine',
        //     result: 'victory' | 'defeat' | 'retreat',
        //     highlights: 'Nat 20 一箭射中了...',
        //     xpGained: 300,
        //     loot: ['治疗药水', '+1 长剑'],
        //     roomsCleared: 4,
        // }

        _version: 1,
        _updatedAt: '',
    };
}

// ═══════════════════════════════════════════════════════════════════════
// Core Read/Write
// ═══════════════════════════════════════════════════════════════════════

/**
 * Load D&D data from localStorage.
 */
export function loadDndData() {
    try {
        const raw = localStorage.getItem(DND_STORAGE_KEY);
        if (!raw) return createDefaultData();
        const parsed = JSON.parse(raw);
        return deepMerge(createDefaultData(), parsed);
    } catch (e) {
        console.warn(`${DND_LOG} loadDndData failed:`, e);
        return createDefaultData();
    }
}

/**
 * Save D&D data to localStorage + async sync to server.
 */
export function saveDndData(data) {
    data._updatedAt = new Date().toISOString();
    try {
        localStorage.setItem(DND_STORAGE_KEY, JSON.stringify(data));
    } catch (e) {
        console.error(`${DND_LOG} saveDndData failed:`, e);
    }
    _syncToServer(data);
}

// ═══════════════════════════════════════════════════════════════════════
// Character Management
// ═══════════════════════════════════════════════════════════════════════

/**
 * Save the player's character.
 */
export function savePlayerCharacter(character) {
    const data = loadDndData();
    data.playerCharacter = character;
    saveDndData(data);
}

/**
 * Save the partner's character (generated by LLM).
 */
export function savePartnerCharacter(character) {
    const data = loadDndData();
    data.partnerCharacter = character;
    saveDndData(data);
}

/**
 * Get player character.
 */
export function getPlayerCharacter() {
    return loadDndData().playerCharacter;
}

/**
 * Get partner character.
 */
export function getPartnerCharacter() {
    return loadDndData().partnerCharacter;
}

/**
 * Check if character creation is complete.
 */
export function hasCharacters() {
    const data = loadDndData();
    return !!(data.playerCharacter && data.partnerCharacter);
}

// ═══════════════════════════════════════════════════════════════════════
// Adventure Run Management
// ═══════════════════════════════════════════════════════════════════════

/**
 * Start a new adventure run.
 */
export function startRun(campaignId, totalRooms) {
    const data = loadDndData();
    data.currentRun = {
        campaignId,
        currentRoom: 0,         // 0 = not yet entered first room
        totalRooms,
        narrativeLog: [],
        roomType: null,
        roomHistory: [],        // track room types for progression guarantees
        roomSummaries: [],      // LLM-generated summaries of completed rooms
        inCombat: false,
        combatState: null,
        startedAt: new Date().toISOString(),
    };
    saveDndData(data);
    return data.currentRun;
}

/**
 * Get current run.
 */
export function getCurrentRun() {
    return loadDndData().currentRun;
}

/**
 * Update current run fields.
 */
export function updateCurrentRun(updates) {
    const data = loadDndData();
    if (!data.currentRun) return null;
    Object.assign(data.currentRun, updates);
    saveDndData(data);
    return data.currentRun;
}

/**
 * Append to the narrative log.
 * Uses debounced writing to avoid excessive localStorage I/O during combat.
 */
let _narrativeBuffer = [];
let _narrativeFlushTimer = null;
const NARRATIVE_FLUSH_MS = 200;

function _flushNarrativeBuffer() {
    if (_narrativeBuffer.length === 0) return;
    const data = loadDndData();
    if (!data.currentRun) { _narrativeBuffer = []; return; }
    data.currentRun.narrativeLog.push(..._narrativeBuffer);
    _narrativeBuffer = [];
    saveDndData(data);
}

export function appendNarrative(type, text) {
    _narrativeBuffer.push({ type, text, timestamp: Date.now() });
    if (_narrativeFlushTimer) clearTimeout(_narrativeFlushTimer);
    _narrativeFlushTimer = setTimeout(_flushNarrativeBuffer, NARRATIVE_FLUSH_MS);
}

/** Force-flush any pending narrative entries (call before reading narrativeLog). */
export function flushNarrative() {
    if (_narrativeFlushTimer) clearTimeout(_narrativeFlushTimer);
    _flushNarrativeBuffer();
}

/**
 * Advance to the next room.
 */
export function advanceRoom(roomType) {
    const data = loadDndData();
    if (!data.currentRun) return null;
    data.currentRun.currentRoom += 1;
    data.currentRun.roomType = roomType;
    if (!data.currentRun.roomHistory) data.currentRun.roomHistory = [];
    data.currentRun.roomHistory.push(roomType);
    data.currentRun.inCombat = false;
    data.currentRun.combatState = null;
    saveDndData(data);
    return data.currentRun;
}

/**
 * Update HP for player or partner.
 * @param {'player'|'partner'} who
 * @param {number} newHP
 */
export function updateHP(who, newHP) {
    const data = loadDndData();
    const char = who === 'player' ? data.playerCharacter : data.partnerCharacter;
    if (!char) return;
    char.currentHP = Math.max(0, Math.min(newHP, char.maxHP));
    saveDndData(data);
}

/**
 * Use an item from inventory.
 * @returns {boolean} true if item was found and used
 */
export function useItem(who, itemName) {
    const data = loadDndData();
    const char = who === 'player' ? data.playerCharacter : data.partnerCharacter;
    if (!char) return false;
    const idx = char.inventory.indexOf(itemName);
    if (idx === -1) return false;
    char.inventory.splice(idx, 1);
    saveDndData(data);
    return true;
}

/**
 * Set combat state on the current run.
 */
export function setCombatState(combatState) {
    const data = loadDndData();
    if (!data.currentRun) return;
    data.currentRun.combatState = combatState;
    saveDndData(data);
}

/**
 * Get combat state from the current run.
 */
export function getCombatState() {
    return loadDndData().currentRun?.combatState || null;
}

/**
 * Set the inCombat flag on the current run.
 */
export function setInCombat(flag) {
    const data = loadDndData();
    if (!data.currentRun) return;
    data.currentRun.inCombat = flag;
    if (!flag) data.currentRun.combatState = null;
    saveDndData(data);
}

/**
 * Add an LLM-generated summary for a completed room.
 * @param {string} summary — 100-200 char summary of what happened in the room
 */
export function addRoomSummary(summary) {
    const data = loadDndData();
    if (!data.currentRun) return;
    if (!data.currentRun.roomSummaries) data.currentRun.roomSummaries = [];
    data.currentRun.roomSummaries.push(summary);
    saveDndData(data);
}

/**
 * Get all room summaries for the current run.
 * @returns {string[]}
 */
export function getRoomSummaries() {
    const run = loadDndData().currentRun;
    return run?.roomSummaries || [];
}

/**
 * Build the narrativeContext object for LLM prompt injection.
 * Flushes pending narrative first, then returns last N entries + room summaries.
 * @param {number} [recentCount=20] — how many recent narrative entries to include
 * @returns {{ recentEntries: Array<{type:string, text:string}>, roomSummaries: string[] }}
 */
export function getNarrativeContext(recentCount = 20) {
    flushNarrative(); // ensure all buffered entries are written
    const run = loadDndData().currentRun;
    if (!run) return { recentEntries: [], roomSummaries: [] };
    const log = run.narrativeLog || [];
    return {
        recentEntries: log.slice(-recentCount),
        roomSummaries: run.roomSummaries || [],
    };
}

/**
 * Add loot to player inventory.
 */
export function addLoot(itemName) {
    const data = loadDndData();
    if (!data.playerCharacter) return;
    data.playerCharacter.inventory.push(itemName);
    saveDndData(data);
}

/**
 * End the current run and move to history.
 */
export function endRun(result, highlights, xpGained, loot) {
    const data = loadDndData();
    if (!data.currentRun) return;

    const campaignId = data.currentRun.campaignId;
    const campaignInfo = getCampaignById(campaignId);
    const roomsCleared = data.currentRun.currentRoom;

    data.history.push({
        date: new Date().toISOString().split('T')[0],
        campaign: campaignInfo?.name || campaignId,
        campaignId: campaignId,
        result,
        highlights: highlights || '',
        xpGained: xpGained || 0,
        loot: loot || [],
        roomsCleared,
    });

    // Add XP to player character
    if (data.playerCharacter && xpGained) {
        data.playerCharacter.xp = (data.playerCharacter.xp || 0) + xpGained;
    }

    // Restore HP for long rest after adventure
    if (data.playerCharacter) {
        data.playerCharacter.currentHP = data.playerCharacter.maxHP;
        // Restore spell slots
        if (data.playerCharacter.maxSpellSlots) {
            data.playerCharacter.spellSlots = { ...data.playerCharacter.maxSpellSlots };
        }
        // Restore hit dice
        if (data.playerCharacter.hitDice) {
            data.playerCharacter.hitDice.remaining = data.playerCharacter.hitDice.total;
        }
        // Reset death saves
        data.playerCharacter.deathSaves = { successes: 0, failures: 0 };
    }
    if (data.partnerCharacter) {
        data.partnerCharacter.currentHP = data.partnerCharacter.maxHP;
        // Restore partner spell slots too (long rest)
        if (data.partnerCharacter.maxSpellSlots) {
            data.partnerCharacter.spellSlots = { ...data.partnerCharacter.maxSpellSlots };
        }
        // Restore partner hit dice
        if (data.partnerCharacter.hitDice) {
            data.partnerCharacter.hitDice.remaining = data.partnerCharacter.hitDice.total;
        }
        data.partnerCharacter.deathSaves = { successes: 0, failures: 0 };
    }

    // Award gold
    if (data.playerCharacter && result !== 'defeat') {
        const goldGain = (roomsCleared || 1) * 25;
        data.playerCharacter.gold = (data.playerCharacter.gold || 0) + goldGain;
    }

    data.currentRun = null;
    saveDndData(data);
}

/**
 * Reset all D&D data.
 */
export function resetDndData() {
    const data = createDefaultData();
    saveDndData(data);
    return data;
}

// ═══════════════════════════════════════════════════════════════════════
// Server Sync (fire-and-forget, debounced)
// ═══════════════════════════════════════════════════════════════════════

let _syncTimer = null;
const SYNC_DEBOUNCE_MS = 3000;

function _syncToServer(data) {
    const settings = getSettings();
    if (!settings.backendUrl || !settings.userId) return;

    if (_syncTimer) clearTimeout(_syncTimer);
    _syncTimer = setTimeout(async () => {
        try {
            await apiRequest('POST', `/api/dnd/${encodeURIComponent(settings.userId)}`, { data });
            console.log(`${DND_LOG} 数据已同步到服务器`);
        } catch (e) {
            console.warn(`${DND_LOG} 服务器同步失败:`, e.message);
        }
    }, SYNC_DEBOUNCE_MS);
}

/**
 * Initialize from server (pull + compare timestamps).
 */
export async function initDndDataFromServer() {
    let localData = null;
    let localTime = 0;
    const raw = localStorage.getItem(DND_STORAGE_KEY);
    if (raw) {
        try {
            const parsed = JSON.parse(raw);
            if (parsed) {
                localData = deepMerge(createDefaultData(), parsed);
                localTime = localData._updatedAt ? new Date(localData._updatedAt).getTime() : 0;
            }
        } catch (e) { /* ignore */ }
    }

    const settings = getSettings();
    let serverData = null;
    let serverTime = 0;
    if (settings.backendUrl && settings.userId) {
        try {
            const result = await apiRequest('GET', `/api/dnd/${encodeURIComponent(settings.userId)}`);
            if (result?.data) {
                serverData = deepMerge(createDefaultData(), result.data);
                serverTime = serverData._updatedAt ? new Date(serverData._updatedAt).getTime() : 0;
            }
        } catch (e) {
            console.warn(`${DND_LOG} 从服务器拉取失败:`, e.message);
        }
    }

    if (serverData && localData) {
        if (localTime > serverTime) {
            _syncToServer(localData);
            return localData;
        } else {
            localStorage.setItem(DND_STORAGE_KEY, JSON.stringify(serverData));
            return serverData;
        }
    } else if (serverData) {
        localStorage.setItem(DND_STORAGE_KEY, JSON.stringify(serverData));
        return serverData;
    } else if (localData) {
        _syncToServer(localData);
        return localData;
    }

    return createDefaultData();
}

// ═══════════════════════════════════════════════════════════════════════
// Utility
// ═══════════════════════════════════════════════════════════════════════

function deepMerge(target, source) {
    const result = { ...target };
    for (const key of Object.keys(source)) {
        if (
            source[key] !== null &&
            typeof source[key] === 'object' &&
            !Array.isArray(source[key]) &&
            target[key] !== null &&
            typeof target[key] === 'object' &&
            !Array.isArray(target[key])
        ) {
            result[key] = deepMerge(target[key], source[key]);
        } else {
            result[key] = source[key];
        }
    }
    return result;
}
